
@host = http://localhost:2298/api
@contentType = application/json

#id = 8
#@authorization = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4IiwidW5pcXVlX25hbWUiOiJzdXNpZSIsIm5iZiI6MTU0ODgzMTU3NywiZXhwIjoxNTQ4OTE3OTc3LCJpYXQiOjE1NDg4MzE1Nzd9.vXe5BL0bEI88rxVNAY0XnDYEqLRnDoJSPnGDn4oJdmywMYfZZws8jO3KSWUl6QBQn0QPZsWHMiHeNfi_UPMydQ

#id = 1
@authorization = bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJ3YWxsZXIiLCJuYmYiOjE1NDg5NTkyMzQsImV4cCI6MTU0OTA0NTYzNCwiaWF0IjoxNTQ4OTU5MjM0fQ.YgmbadnfuIFIjH0nrJcUhv-MX3Ce6mWCKXWdNPk7WDeXTjOz2Xk0AcfBp9m0lrpWP1vOIM-74thZct0X2mS54g
###

POST {{host}}/auth/register HTTP/1.1
Content-Type: {{contentType}}

{
    "gender": "male",
    "username": "test3",
    "password": "password",
    "knownAs": "nickname",
    "dateOfBirth": "11/11/1918",
    "city": "Czestochowa",
    "country": "Poland"
}

###

POST {{host}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "userName": "waller",
    "password": "password"
}

###
GET {{host}}/users HTTP/1.1
Authorization: {{authorization}}

###
GET {{host}}/users/15 HTTP/1.1
Authorization: {{authorization}}

###
GET {{host}}/users HTTP/1.1
Authorization: {{authorization}}
###
GET {{host}}/users HTTP/1.1
Authorization: {{authorization}}
###
POST {{host}}/users/15/photos/20/setmain HTTP/1.1
Authorization: {{authorization}}

###
DELETE  {{host}}/users/15/photos/14 HTTP/1.1
Authorization: {{authorization}}

###
POST {{host}}/users/1/like/5 HTTP/1.1
Authorization: {{authorization}}
###
GET {{host}}/users?likees=true HTTP/1.1
Authorization: {{authorization}}
###
POST {{host}}/users/1/messages HTTP/1.1
Content-Type: {{contentType}}
Authorization: {{authorization}}

{
    "recipientId": "2",
    "content": "test"
}
###
Get {{host}}/users/1/messages/1 HTTP/1.1
Authorization: {{authorization}}
###
Get {{host}}/users/1/messages?messageContainer=outbox HTTP/1.1
Authorization: {{authorization}}

###
Get {{host}}/users/1/messages/thread/2 HTTP/1.1
Authorization: {{authorization}}
